services:
  barcode-service:
    image: barcode-service:latest
    build:
      context: .
      dockerfile: barcode-service/Dockerfile
      platforms:
        - linux/amd64
    container_name: barcode-service
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped

  web-service:
    image: web-service:latest
    build:
      context: .
      dockerfile: web-service/Dockerfile
      platforms:
        - linux/amd64
    container_name: web-service
    ports:
      - "127.0.0.1:8081:8081"
    restart: unless-stopped