services:
  barcode-service:
    image: barcode-service:latest
    container_name: barcode-service
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped

  web-service:
    image: web-service:latest
    container_name: web-service
    ports:
      - "127.0.0.1:8081:8081"
    restart: unless-stopped